import { SonnerToaster } from "@/components/sonner/Sonner";
import { SITE_NAME } from "@/constants/seo.constants";
import type { Metadata } from "next";
import localFont from "next/font/local";
import AppHeader from "./AppHeader";
import AppSidebar from "./AppSidebar";
import "./globals.scss";
import Providers from "./Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: SITE_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <Providers>
          <AppSidebar />
          <main className="w-full">
            <AppHeader />
            {children}
          </main>
        </Providers>
        <SonnerToaster />
      </body>
    </html>
  );
}
